#!/usr/bin/env bash
#display information about subdomains

get_subdomain() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
        dest=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
        echo "The subdomain $sub is a $record_type record and points to $dest"
    done
}

get_subdomain "$1" "$2"
