#!/usr/bin/env bash
#steps to install ngix server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx status
sudo netstat -tuln | grep :80
sudo lsof -i6:80
sudo service apache2 stop
sudo service nginx start
