#!/usr/bin/env bash
# install Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl status nginx
sudo nginx -t
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
sudo netstat -tuln | grep LISTEN | grep :80
