#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# username, user id, Home directory path for the user
file="/etc/passwd"
while IFS= read -r line
do
    username=$(echo "$line" | cut -d: -f1)
    user_id=$(echo "$line" | cut -d: -f3)
    home_directory=$(echo "$line" | cut -d: -f6)
    echo "$username:$user_id:$home_directory"
done < "$file"
