#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.
#!/usr/bin/env bash

# Read the /etc/passwd file line by line
file="/etc/passwd"
while IFS=: read -r username password user_id group_id user_info home_directory command
do
    echo "The user $username is part of the $group_id gang, lives in $home_directory, and rides $command. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < "$file"

