#!/usr/bin/env bash
#run Nginx
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g; s/#user www-data;/user nginx;/g; s/80/8080/g' /etc/apache2/ports.conf /etc/nginx/nginx.conf /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
